### ISSUE TITLE
Feature Request: Ability to use a dump as the input

### ISSUE THREAD

**Issue by sdushantha** [skyf0l/RsaCracker#18]
Hey there!

First of all, thank you for creating this powerful tool. I've used this program quite a bit now and it has worked very well :)

One feature I wish `rsacracker` had is the ability to use a dump as the input. I often see in CTF challenges that they provide data like shown below:

```
c: 78394077185972242522366494812194999029111007804513916081388100744678077142246684573709463174914072230588766938274935729449697899122556506361108922139286130431073819269477944903949010409297739704373353086560177410340042335176831160010922826152074048460889509110907225759217407138633733239524781798190577093673
n: 93596195645610503452177719837666902345047461004926714393186384188598288812343005592124086521572864457489909063543756427769917131437307447863586528928496194559057760628385975297585140789577911616474493538014622500120560643072265673362843715324209056486085041020831625385434745566998218712055519575753745124619
e: 1595235523996321655798747471789583440185208568327862733680046250799766370193739982702940394656406146131440688831932739213253542820322450207724280220533900355744553772981019201731036379810734890063829650829319133004906034534031330743611288482822751674556919861911431941749713177767003275664528498846275096193
```
_Source: PicoCTF2019 b00tl3gRSA2_

I usually copy each value and add it to `rsacracker` using `-c`, `-n`, and `-e`.  This may be a tedious process at times, and it would be amazing if there were the ability to give `rsacracker` a file containing data as shown above.

In the code snippet shown above, the key and values are separated using a colon (`:`), but I've also seen in many challenges that the equal sign (`=`) is used instead. This is something we also see when we execute `rsacracker` using the `--dump` flag.

**Comment by skyf0l** [comment]
Thanks for your feedback, I put it in my backlog!

**Comment by skyf0l** [comment]
Hello @sdushantha, 

Just implemented in the latest version.
`--dump` was already used but you can now use:
```
$ rsacracker [OPTIONS...] < challenge.txt
$ cat challenge.txt | rsacracker [OPTIONS...]
```
